### ISSUE TITLE
QGC切换offboard模式，并悬停的问题。

### ISSUE THREAD

**Issue by SSZ1** [zhongtianda/px4_gazebo_fuel#4]
您好，看到您的知乎里面的说明教程，我按照流程到了“启动qgc，切offboard模式，然后解锁。可以看到无人机起飞到一定高度悬停。”   这一步，想咨询您一下怎么在仿真情况下使用QGC切换offboard模式？切换之后解锁飞机是在这个位置解锁吗？ 感谢您不吝赐教！
![image](https://github.com/zhongtianda/px4_gazebo_fuel/assets/36888758/2dfa57e4-df97-4eee-8b88-b4edeb1d44ae)

**Comment by zhongtianda** [comment]
点击等待那个位置，切offboard模式，然后点击这个arm，下方滑动解锁

**Comment by SSZ1** [comment]
> 点击等待那个位置，切offboard模式，然后点击这个arm，下方滑动解锁

好的好的，太感谢了！！！

**Comment by SSZ1** [comment]
> 点击等待那个位置，切offboard模式，然后点击这个arm，下方滑动解锁

还想咨询一下，这个控制脚本的控制方式也可以直接接入ego planner输出的控制指令吧。

**Comment by zhongtianda** [comment]
可以，写代码转换成符合setpoint_raw那个话题的数据格式，最好设置一些界限，防止ego的规划出错

**Comment by SSZ1** [comment]
> 可以，写代码转换成符合setpoint_raw那个话题的数据格式，最好设置一些界限，防止ego的规划出错

谢谢大佬！这套代码应该也可以直接应用到实机上吧。启动控制节点，切换到 offboard，然后解锁飞机，飞机自动悬停到1m处。

**Comment by SSZ1** [comment]
感谢大佬解决了，我的问题，我关闭issue了。
