### ISSUE TITLE
关于 ego_transfer.py的问题

### ISSUE THREAD

**Issue by SSZ1** [zhongtianda/px4_gazebo_fuel#5]
阅读了ego_transfer.py的代码，有一点疑问，想问下大佬，获取飞机的位姿真值之后，又做了ego transfer'的变换，在表示飞机位姿的四元数旁边右乘了一个quaternion = tf.transformations.quaternion_from_euler(-math.pi/2, 0, -math.pi/2)  的旋转，不太理解，这个旋转旋转之后是把飞机姿态转换成realsense的姿态了吗？

**Comment by zhongtianda** [comment]
就是把无人机的位姿经过旋转和平移，得到相机的位姿，因为fule的输入有一个是相机的poso。机体坐标是前左上，相机是右下前

**Comment by SSZ1** [comment]
> 就是把无人机的位姿经过旋转和平移，得到相机的位姿，因为fule的输入有一个是相机的poso。机体坐标是前左上，相机是右下前

我现在看明白了，谢谢大佬！
